FManC: src/analyze.c File Reference
analyze.c File Reference
Functions
size_t countCharInFile (char *filePath)
void free_stringOccurrences (stringOccurrences *toBeDeleted)
stringOccurrences * init_StringOccurences (size_t sizeOfString)
int replaceStringInFile (char *filePath, char *toReplaceString, char *toAddString)
stringOccurrences * searchStringInFile (char *filePath, char *toSearch)
Function Documentation
countCharInFile()
size_t countCharInFile (char * filePath)
Definition at line 14 of file analyze.c.
Referenced by searchStringInFile().
free_stringOccurrences()
void free_stringOccurrences (stringOccurrences * toBeDeleted)
Definition at line 47 of file analyze.c.
References FMANC_SO::pos.
Referenced by replaceStringInFile(), and searchStringInFile().
init_StringOccurences()
stringOccurrences * init_StringOccurences (size_t sizeOfString)
Definition at line 35 of file analyze.c.
References FMANC_SO::charCount, and FMANC_SO::pos.
Referenced by searchStringInFile().
replaceStringInFile()
int replaceStringInFile (char * filePath, char * toReplaceString, char * toAddString)
Definition at line 155 of file analyze.c.
References FMANC_SO::charCount, free_stringOccurrences(), getFileExtension, getFileName, getFilePath, MAX_FEXT_SIZE, MAX_FNAME_SIZE, MAX_FPATH_SIZE, FMANC_SO::pos, and searchStringInFile().
searchStringInFile()
stringOccurrences * searchStringInFile (char * filePath, char * toSearch)
Definition at line 54 of file analyze.c.
References countCharInFile(), free_stringOccurrences(), getFileName, init_StringOccurences(), and FMANC_SO::pos.
Referenced by replaceStringInFile().