FManC: src/general/utils/FMC_errors.h File Reference
FMC_errors.h File Reference
Macros
#define FMC_ERRORS
#define FMC_makeMsg(err_var_name, argc, ...)
Functions
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_changeStreamTextColorToBlue (FILE *stream)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_changeStreamTextColorToBrightBlue (FILE *stream)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_changeStreamTextColorToBrightCyan (FILE *stream)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_changeStreamTextColorToBrightGreen (FILE *stream)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_changeStreamTextColorToBrightMagenta (FILE *stream)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_changeStreamTextColorToBrightRed (FILE *stream)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_changeStreamTextColorToBrightWhite (FILE *stream)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_changeStreamTextColorToBrightYellow (FILE *stream)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_changeStreamTextColorToCyan (FILE *stream)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_changeStreamTextColorToGreen (FILE *stream)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_changeStreamTextColorToMagenta (FILE *stream)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_changeStreamTextColorToRed (FILE *stream)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_changeStreamTextColorToWhite (FILE *stream)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_changeStreamTextColorToYellow (FILE *stream)
FMC_SHARED FMC_FUNC_NONNULL (1) void FMC_makeMsg_f(char *buff
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printBlueError (FILE *stream, const char *error)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printBlueText (FILE *stream, const char *error)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printBrightBlueError (FILE *stream, const char *error)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printBrightBlueText (FILE *stream, const char *error)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printBrightCyanError (FILE *stream, const char *error)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printBrightCyanText (FILE *stream, const char *error)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printBrightGreenError (FILE *stream, const char *error)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printBrightGreenText (FILE *stream, const char *error)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printBrightMagentaError (FILE *stream, const char *error)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printBrightMagentaText (FILE *stream, const char *error)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printBrightRedError (FILE *stream, const char *error)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printBrightRedText (FILE *stream, const char *error)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printBrightWhiteError (FILE *stream, const char *error)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printBrightWhiteText (FILE *stream, const char *error)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printBrightYellowError (FILE *stream, const char *error)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printBrightYellowText (FILE *stream, const char *error)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printCyanError (FILE *stream, const char *error)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printCyanText (FILE *stream, const char *error)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printGreenError (FILE *stream, const char *error)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printGreenText (FILE *stream, const char *error)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printMagentaError (FILE *stream, const char *error)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printMagentaText (FILE *stream, const char *error)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printRedError (FILE *stream, const char *error)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printRedText (FILE *stream, const char *error)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printWhiteError (FILE *stream, const char *error)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printWhiteText (FILE *stream, const char *error)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printYellowError (FILE *stream, const char *error)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printYellowText (FILE *stream, const char *error)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_resetStreamOutputStyle (FILE *stream)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_setBGStreamColorToBlue (FILE *stream)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_setBGStreamColorToBrightBlue (FILE *stream)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_setBGStreamColorToBrightCyan (FILE *stream)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_setBGStreamColorToBrightGreen (FILE *stream)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_setBGStreamColorToBrightMagenta (FILE *stream)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_setBGStreamColorToBrightRed (FILE *stream)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_setBGStreamColorToBrightWhite (FILE *stream)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_setBGStreamColorToBrightYellow (FILE *stream)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_setBGStreamColorToCyan (FILE *stream)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_setBGStreamColorToGreen (FILE *stream)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_setBGStreamColorToMagenta (FILE *stream)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_setBGStreamColorToRed (FILE *stream)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_setBGStreamColorToWhite (FILE *stream)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_setBGStreamColorToYellow (FILE *stream)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_setTextStyleToBlink (FILE *stream)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_setTextStyleToBold (FILE *stream)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_setTextStyleToDim (FILE *stream)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_setTextStyleToHidden (FILE *stream)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_setTextStyleToReverse (FILE *stream)
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_setTextStyleToUnderlined (FILE *stream)
Variables
FMC_SHARED unsigned int argc
Macro Definition Documentation
FMC_ERRORS
#define FMC_ERRORS
Definition at line 30 of file FMC_errors.h.
FMC_makeMsg
#define FMC_makeMsg (err_var_name, argc, ...)
Value:
    char err_var_name[256] = {"\0"};                 \
    FMC_makeMsg_f(err_var_name, argc, __VA_ARGS__)
Definition at line 38 of file FMC_errors.h.
Function Documentation
FMC_changeStreamTextColorToBlue()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_changeStreamTextColorToBlue (FILE * stream)
Definition at line 63 of file FMC_errors.h.
References FG_BLUE.
Referenced by FMC_printBlueError(), and FMC_printBlueText().
FMC_changeStreamTextColorToBrightBlue()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_changeStreamTextColorToBrightBlue (FILE * stream)
Definition at line 98 of file FMC_errors.h.
References FG_BRIGHT_BLUE.
Referenced by FMC_printBrightBlueError(), and FMC_printBrightBlueText().
FMC_changeStreamTextColorToBrightCyan()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_changeStreamTextColorToBrightCyan (FILE * stream)
Definition at line 108 of file FMC_errors.h.
References FG_BRIGHT_CYAN.
Referenced by FMC_printBrightCyanError(), and FMC_printBrightCyanText().
FMC_changeStreamTextColorToBrightGreen()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_changeStreamTextColorToBrightGreen (FILE * stream)
Definition at line 88 of file FMC_errors.h.
References FG_BRIGHT_GREEN.
Referenced by FMC_printBrightGreenError(), and FMC_printBrightGreenText().
FMC_changeStreamTextColorToBrightMagenta()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_changeStreamTextColorToBrightMagenta (FILE * stream)
Definition at line 103 of file FMC_errors.h.
References FG_BRIGHT_MAGENTA.
Referenced by FMC_printBrightMagentaError(), and FMC_printBrightMagentaText().
FMC_changeStreamTextColorToBrightRed()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_changeStreamTextColorToBrightRed (FILE * stream)
Definition at line 83 of file FMC_errors.h.
References FG_BRIGHT_RED.
Referenced by FMC_printBrightRedError(), and FMC_printBrightRedText().
FMC_changeStreamTextColorToBrightWhite()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_changeStreamTextColorToBrightWhite (FILE * stream)
Definition at line 113 of file FMC_errors.h.
References FG_BRIGHT_WHITE.
Referenced by FMC_printBrightWhiteError(), and FMC_printBrightWhiteText().
FMC_changeStreamTextColorToBrightYellow()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_changeStreamTextColorToBrightYellow (FILE * stream)
Definition at line 93 of file FMC_errors.h.
References FG_BRIGHT_YELLOW.
Referenced by FMC_printBrightYellowError(), and FMC_printBrightYellowText().
FMC_changeStreamTextColorToCyan()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_changeStreamTextColorToCyan (FILE * stream)
Definition at line 73 of file FMC_errors.h.
References FG_CYAN.
Referenced by FMC_printCyanError(), and FMC_printCyanText().
FMC_changeStreamTextColorToGreen()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_changeStreamTextColorToGreen (FILE * stream)
Definition at line 53 of file FMC_errors.h.
References FG_GREEN.
Referenced by FMC_printGreenError(), and FMC_printGreenText().
FMC_changeStreamTextColorToMagenta()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_changeStreamTextColorToMagenta (FILE * stream)
Definition at line 68 of file FMC_errors.h.
References FG_MAGENTA.
Referenced by FMC_printMagentaError(), and FMC_printMagentaText().
FMC_changeStreamTextColorToRed()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_changeStreamTextColorToRed (FILE * stream)
Definition at line 48 of file FMC_errors.h.
References FG_RED.
Referenced by FMC_printRedError(), and FMC_printRedText().
FMC_changeStreamTextColorToWhite()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_changeStreamTextColorToWhite (FILE * stream)
Definition at line 78 of file FMC_errors.h.
References FG_WHITE.
Referenced by FMC_printWhiteError(), and FMC_printWhiteText().
FMC_changeStreamTextColorToYellow()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_changeStreamTextColorToYellow (FILE * stream)
Definition at line 58 of file FMC_errors.h.
References FG_YELLOW.
Referenced by FMC_printYellowError(), and FMC_printYellowText().
FMC_FUNC_NONNULL()
FMC_SHARED FMC_FUNC_NONNULL (1)
Definition at line 34 of file FMC_encodings.c.
FMC_printBlueError()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printBlueError (FILE * stream, const char * error)
Definition at line 341 of file FMC_errors.h.
References error, FMC_changeStreamTextColorToBlue(), FMC_resetStreamOutputStyle(), and FMC_setTextStyleToBold().
FMC_printBlueText()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printBlueText (FILE * stream, const char * error)
Definition at line 240 of file FMC_errors.h.
References error, FMC_changeStreamTextColorToBlue(), and FMC_resetStreamOutputStyle().
FMC_printBrightBlueError()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printBrightBlueError (FILE * stream, const char * error)
Definition at line 397 of file FMC_errors.h.
References error, FMC_changeStreamTextColorToBrightBlue(), FMC_resetStreamOutputStyle(), and FMC_setTextStyleToBold().
FMC_printBrightBlueText()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printBrightBlueText (FILE * stream, const char * error)
Definition at line 289 of file FMC_errors.h.
References error, FMC_changeStreamTextColorToBrightBlue(), and FMC_resetStreamOutputStyle().
FMC_printBrightCyanError()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printBrightCyanError (FILE * stream, const char * error)
Definition at line 413 of file FMC_errors.h.
References error, FMC_changeStreamTextColorToBrightCyan(), FMC_resetStreamOutputStyle(), and FMC_setTextStyleToBold().
FMC_printBrightCyanText()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printBrightCyanText (FILE * stream, const char * error)
Definition at line 303 of file FMC_errors.h.
References error, FMC_changeStreamTextColorToBrightCyan(), and FMC_resetStreamOutputStyle().
FMC_printBrightGreenError()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printBrightGreenError (FILE * stream, const char * error)
Definition at line 381 of file FMC_errors.h.
References error, FMC_changeStreamTextColorToBrightGreen(), FMC_resetStreamOutputStyle(), and FMC_setTextStyleToBold().
FMC_printBrightGreenText()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printBrightGreenText (FILE * stream, const char * error)
Definition at line 275 of file FMC_errors.h.
References error, FMC_changeStreamTextColorToBrightGreen(), and FMC_resetStreamOutputStyle().
FMC_printBrightMagentaError()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printBrightMagentaError (FILE * stream, const char * error)
Definition at line 405 of file FMC_errors.h.
References error, FMC_changeStreamTextColorToBrightMagenta(), FMC_resetStreamOutputStyle(), and FMC_setTextStyleToBold().
FMC_printBrightMagentaText()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printBrightMagentaText (FILE * stream, const char * error)
Definition at line 296 of file FMC_errors.h.
References error, FMC_changeStreamTextColorToBrightMagenta(), and FMC_resetStreamOutputStyle().
FMC_printBrightRedError()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printBrightRedError (FILE * stream, const char * error)
Definition at line 373 of file FMC_errors.h.
References error, FMC_changeStreamTextColorToBrightRed(), FMC_resetStreamOutputStyle(), and FMC_setTextStyleToBold().
Referenced by FMC_FUNC_NONNULL().
FMC_printBrightRedText()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printBrightRedText (FILE * stream, const char * error)
Definition at line 268 of file FMC_errors.h.
References error, FMC_changeStreamTextColorToBrightRed(), and FMC_resetStreamOutputStyle().
FMC_printBrightWhiteError()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printBrightWhiteError (FILE * stream, const char * error)
Definition at line 421 of file FMC_errors.h.
References error, FMC_changeStreamTextColorToBrightWhite(), FMC_resetStreamOutputStyle(), and FMC_setTextStyleToBold().
FMC_printBrightWhiteText()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printBrightWhiteText (FILE * stream, const char * error)
Definition at line 310 of file FMC_errors.h.
References error, FMC_changeStreamTextColorToBrightWhite(), and FMC_resetStreamOutputStyle().
FMC_printBrightYellowError()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printBrightYellowError (FILE * stream, const char * error)
Definition at line 389 of file FMC_errors.h.
References error, FMC_changeStreamTextColorToBrightYellow(), FMC_resetStreamOutputStyle(), and FMC_setTextStyleToBold().
Referenced by FMC_FUNC_NONNULL().
FMC_printBrightYellowText()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printBrightYellowText (FILE * stream, const char * error)
Definition at line 282 of file FMC_errors.h.
References error, FMC_changeStreamTextColorToBrightYellow(), and FMC_resetStreamOutputStyle().
FMC_printCyanError()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printCyanError (FILE * stream, const char * error)
Definition at line 357 of file FMC_errors.h.
References error, FMC_changeStreamTextColorToCyan(), FMC_resetStreamOutputStyle(), and FMC_setTextStyleToBold().
FMC_printCyanText()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printCyanText (FILE * stream, const char * error)
Definition at line 254 of file FMC_errors.h.
References error, FMC_changeStreamTextColorToCyan(), and FMC_resetStreamOutputStyle().
FMC_printGreenError()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printGreenError (FILE * stream, const char * error)
Definition at line 325 of file FMC_errors.h.
References error, FMC_changeStreamTextColorToGreen(), FMC_resetStreamOutputStyle(), and FMC_setTextStyleToBold().
FMC_printGreenText()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printGreenText (FILE * stream, const char * error)
Definition at line 226 of file FMC_errors.h.
References error, FMC_changeStreamTextColorToGreen(), and FMC_resetStreamOutputStyle().
FMC_printMagentaError()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printMagentaError (FILE * stream, const char * error)
Definition at line 349 of file FMC_errors.h.
References error, FMC_changeStreamTextColorToMagenta(), FMC_resetStreamOutputStyle(), and FMC_setTextStyleToBold().
FMC_printMagentaText()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printMagentaText (FILE * stream, const char * error)
Definition at line 247 of file FMC_errors.h.
References error, FMC_changeStreamTextColorToMagenta(), and FMC_resetStreamOutputStyle().
FMC_printRedError()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printRedError (FILE * stream, const char * error)
Definition at line 317 of file FMC_errors.h.
References error, FMC_changeStreamTextColorToRed(), FMC_resetStreamOutputStyle(), and FMC_setTextStyleToBold().
FMC_printRedText()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printRedText (FILE * stream, const char * error)
Definition at line 219 of file FMC_errors.h.
References error, FMC_changeStreamTextColorToRed(), and FMC_resetStreamOutputStyle().
FMC_printWhiteError()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printWhiteError (FILE * stream, const char * error)
Definition at line 365 of file FMC_errors.h.
References error, FMC_changeStreamTextColorToWhite(), FMC_resetStreamOutputStyle(), and FMC_setTextStyleToBold().
FMC_printWhiteText()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printWhiteText (FILE * stream, const char * error)
Definition at line 261 of file FMC_errors.h.
References error, FMC_changeStreamTextColorToWhite(), and FMC_resetStreamOutputStyle().
FMC_printYellowError()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printYellowError (FILE * stream, const char * error)
Definition at line 333 of file FMC_errors.h.
References error, FMC_changeStreamTextColorToYellow(), FMC_resetStreamOutputStyle(), and FMC_setTextStyleToBold().
FMC_printYellowText()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_printYellowText (FILE * stream, const char * error)
Definition at line 233 of file FMC_errors.h.
References error, FMC_changeStreamTextColorToYellow(), and FMC_resetStreamOutputStyle().
FMC_resetStreamOutputStyle()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_resetStreamOutputStyle (FILE * stream)
Definition at line 42 of file FMC_errors.h.
References RESET.
Referenced by FMC_printBlueError(), FMC_printBlueText(), FMC_printBrightBlueError(), FMC_printBrightBlueText(), FMC_printBrightCyanError(), FMC_printBrightCyanText(), FMC_printBrightGreenError(), FMC_printBrightGreenText(), FMC_printBrightMagentaError(), FMC_printBrightMagentaText(), FMC_printBrightRedError(), FMC_printBrightRedText(), FMC_printBrightWhiteError(), FMC_printBrightWhiteText(), FMC_printBrightYellowError(), FMC_printBrightYellowText(), FMC_printCyanError(), FMC_printCyanText(), FMC_printGreenError(), FMC_printGreenText(), FMC_printMagentaError(), FMC_printMagentaText(), FMC_printRedError(), FMC_printRedText(), FMC_printWhiteError(), FMC_printWhiteText(), FMC_printYellowError(), and FMC_printYellowText().
FMC_setBGStreamColorToBlue()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_setBGStreamColorToBlue (FILE * stream)
Definition at line 133 of file FMC_errors.h.
References BG_BLUE.
FMC_setBGStreamColorToBrightBlue()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_setBGStreamColorToBrightBlue (FILE * stream)
Definition at line 168 of file FMC_errors.h.
References BG_BRIGHT_BLUE.
FMC_setBGStreamColorToBrightCyan()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_setBGStreamColorToBrightCyan (FILE * stream)
Definition at line 178 of file FMC_errors.h.
References BG_BRIGHT_CYAN.
FMC_setBGStreamColorToBrightGreen()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_setBGStreamColorToBrightGreen (FILE * stream)
Definition at line 158 of file FMC_errors.h.
References BG_BRIGHT_GREEN.
FMC_setBGStreamColorToBrightMagenta()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_setBGStreamColorToBrightMagenta (FILE * stream)
Definition at line 173 of file FMC_errors.h.
References BG_BRIGHT_MAGENTA.
FMC_setBGStreamColorToBrightRed()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_setBGStreamColorToBrightRed (FILE * stream)
Definition at line 153 of file FMC_errors.h.
References BG_BRIGHT_RED.
FMC_setBGStreamColorToBrightWhite()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_setBGStreamColorToBrightWhite (FILE * stream)
Definition at line 183 of file FMC_errors.h.
References BG_BRIGHT_WHITE.
FMC_setBGStreamColorToBrightYellow()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_setBGStreamColorToBrightYellow (FILE * stream)
Definition at line 163 of file FMC_errors.h.
References BG_BRIGHT_YELLOW.
FMC_setBGStreamColorToCyan()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_setBGStreamColorToCyan (FILE * stream)
Definition at line 143 of file FMC_errors.h.
References BG_CYAN.
FMC_setBGStreamColorToGreen()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_setBGStreamColorToGreen (FILE * stream)
Definition at line 123 of file FMC_errors.h.
References BG_GREEN.
FMC_setBGStreamColorToMagenta()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_setBGStreamColorToMagenta (FILE * stream)
Definition at line 138 of file FMC_errors.h.
References BG_MAGENTA.
FMC_setBGStreamColorToRed()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_setBGStreamColorToRed (FILE * stream)
Definition at line 118 of file FMC_errors.h.
References BG_RED.
FMC_setBGStreamColorToWhite()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_setBGStreamColorToWhite (FILE * stream)
Definition at line 148 of file FMC_errors.h.
References BG_WHITE.
FMC_setBGStreamColorToYellow()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_setBGStreamColorToYellow (FILE * stream)
Definition at line 128 of file FMC_errors.h.
References BG_YELLOW.
FMC_setTextStyleToBlink()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_setTextStyleToBlink (FILE * stream)
Definition at line 203 of file FMC_errors.h.
References TXT_BLINK.
FMC_setTextStyleToBold()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_setTextStyleToBold (FILE * stream)
Definition at line 188 of file FMC_errors.h.
References TXT_BOLD.
Referenced by FMC_printBlueError(), FMC_printBrightBlueError(), FMC_printBrightCyanError(), FMC_printBrightGreenError(), FMC_printBrightMagentaError(), FMC_printBrightRedError(), FMC_printBrightWhiteError(), FMC_printBrightYellowError(), FMC_printCyanError(), FMC_printGreenError(), FMC_printMagentaError(), FMC_printRedError(), FMC_printWhiteError(), and FMC_printYellowError().
FMC_setTextStyleToDim()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_setTextStyleToDim (FILE * stream)
Definition at line 193 of file FMC_errors.h.
References TXT_DIM.
FMC_setTextStyleToHidden()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_setTextStyleToHidden (FILE * stream)
Definition at line 213 of file FMC_errors.h.
References TXT_HIDDEN.
FMC_setTextStyleToReverse()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_setTextStyleToReverse (FILE * stream)
Definition at line 208 of file FMC_errors.h.
References TXT_REVERSE.
FMC_setTextStyleToUnderlined()
FMC_FUNC_FLATTEN FMC_FUNC_INLINE void FMC_setTextStyleToUnderlined (FILE * stream)
Definition at line 198 of file FMC_errors.h.
References TXT_UNDERLINED.
Variable Documentation
argc
FMC_SHARED unsigned int argc
Definition at line 36 of file FMC_errors.h.
Referenced by FMC_makeMsg_f().