FManC: src/files/FMC_paths.c File Reference
FMC_paths.c File Reference
Functions
char * FMC_cutFilename (const char *restrict const path, char *restrict dirs, const size_t dirs_size)
char * FMC_extractFilename (const char *restrict const path, char *restrict filename, const size_t filename_size)
Gets the filename from a complete path.
char * FMC_getExtension (const char *restrict const path, char *restrict ext, const size_t ext_size)
Variables
FMC_Bool FMC_ENABLE_DEBUG FMC_VAR_COMMON
Function Documentation
FMC_cutFilename()
char * FMC_cutFilename (const char *restrict const path, char *restrict dirs, const size_t dirs_size)
Definition at line 117 of file FMC_paths.c.
References FMC_makeMsg, FMC_printBrightRedError(), MAX_FEXT_SIZE, MAX_FNAME_SIZE, and MAX_FPATH_SIZE.
FMC_extractFilename()
char * FMC_extractFilename (const char *restrict const path, char *restrict filename, const size_t filename_size)
Gets the filename from a complete path.
Author
Axel PASCON
Date
2023
Basically, this function only detects the last '/' or '\' character. For example, if the path is "C:\\Users\\someone\\Documents\\MyFile.txt", the function will return "MyFile.txt". If the path is "/home/someone/Desktop", then Desktop will be considered as the filename. This function is designed to only operate on strings, and do not check if the path is valid, is a file or a directory, etc.
Parameters
[in] path The path to extract the filename from.
[out] filename The buffer where the filename will be stored.
[in] filename_size The size of the filename buffer.
Returns
A pointer to the filename buffer.
Return values
NULL If the path is NULL, if the filename buffer is NULL or if an error occured. The error can be viewed by setting FMC_ENABLE_DEBUG to True .
Warning
The filename buffer must be at least as big as the path.
Note
The maximum filename size is MAX_FNAME_SIZE . You can disable some warnings or error messages by defining FMC_ENABLE_DEBUG to False .
Definition at line 40 of file FMC_paths.c.
References FMC_makeMsg, FMC_printBrightRedError(), MAX_FEXT_SIZE, MAX_FNAME_SIZE, and MAX_FPATH_SIZE.
Referenced by FMC_getExtension().
FMC_getExtension()
char * FMC_getExtension (const char *restrict const path, char *restrict ext, const size_t ext_size)
Definition at line 195 of file FMC_paths.c.
References FMC_extractFilename(), FMC_makeMsg, FMC_printBrightRedError(), MAX_FEXT_SIZE, and MAX_FNAME_SIZE.
Variable Documentation
FMC_VAR_COMMON
FMC_Bool FMC_ENABLE_DEBUG FMC_VAR_COMMON
Definition at line 32 of file FMC_paths.c.