FManC: src/cpp/FMC_wrapper.h File Reference
FMC_wrapper.h File Reference
Functions
int FMC_dirExists (const char *path)
Checks if a directory exists.
char * FMC_getAbsolutePath (char *path, char *buffer, const size_t size)
This function converts a relative path into an absolute one.
char * FMC_getCurrentPath (char *path, const size_t size)
This function is equivalent to $PWD in bash.
int FMC_isBlock (const char *path)
Checks if a path is a block device.
int FMC_isCharFile (const char *path)
Checks if a path is a character device.
int FMC_isDir (const char *path)
Checks if a path is a directory.
int FMC_isEmpty (const char *path)
Checks if a directory is empty.
int FMC_isFIFO (const char *path)
Checks if a path is a FIFO.
int FMC_isOther (const char *path)
Checks if a path is of an unknown type.
int FMC_isRegFile (const char *path)
Checks if a path is a regular file.
int FMC_isSocket (const char *path)
Checks if a path is a socket.
int FMC_isSymLink (const char *path)
Checks if a path is a symbolic link.
Function Documentation
FMC_dirExists()
int FMC_dirExists (const char * path)
Checks if a directory exists.
Author
Axel PASCON
Date
2023
This function is a wrapper around the C++ filesystem library assciated function.
Parameters
[in] path The path whose existence is to be checked.
Returns
An integer value.
Return values
1 if the directory exists.
0 if the directory does not exist.
Definition at line 35 of file FMC_dir_wrapper.cpp.
References FMC_dirExists_().
FMC_getAbsolutePath()
char * FMC_getAbsolutePath (char * path, char * buffer, const size_t size)
This function converts a relative path into an absolute one.
Author
Axel PASCON
Date
2023
This function is a wrapper around the C++ filesystem library assciated function.
Parameters
[in] path The path to convert.
[out] buffer The memory buffer to store the absolute path.
[in] size The size of the memory buffer.
Returns
A pointer to the memory buffer.
Return values
NULL if an error occured.
buffer The pointer to the buffer after the call if the function succeeded.
Definition at line 92 of file FMC_dir_wrapper.cpp.
References FMC_getAbsolutePath_().
FMC_getCurrentPath()
char * FMC_getCurrentPath (char * path, const size_t size)
This function is equivalent to $PWD in bash.
Author
Axel PASCON
Date
2023
This function is a wrapper around the C++ filesystem library assciated function.
Parameters
[out] path The memory buffer to store the current path.
[in] size The size of the memory buffer.
Returns
A pointer to the memory buffer.
Return values
NULL if an error occured.
path The pointer to path after the call if the function succeeded.
Definition at line 87 of file FMC_dir_wrapper.cpp.
References FMC_getCurrentPath_().
FMC_isBlock()
int FMC_isBlock (const char * path)
Checks if a path is a block device.
Author
Axel PASCON
Date
2023
This function is a wrapper around the C++ filesystem library assciated function.
Parameters
[in] path The path to check.
Returns
An integer value.
Return values
1 if the path is a block device.
0 if the path is not a block device.
-1 if an error occured.
Definition at line 55 of file FMC_dir_wrapper.cpp.
References FMC_isBlock_().
FMC_isCharFile()
int FMC_isCharFile (const char * path)
Checks if a path is a character device.
Author
Axel PASCON
Date
2023
This function is a wrapper around the C++ filesystem library assciated function.
Parameters
[in] path The path to check.
Returns
An integer value.
Return values
1 if the path is a character device.
0 if the path is not a character device.
-1 if an error occured.
Definition at line 60 of file FMC_dir_wrapper.cpp.
References FMC_isCharFile_().
FMC_isDir()
int FMC_isDir (const char * path)
Checks if a path is a directory.
Author
Axel PASCON
Date
2023
This function is a wrapper around the C++ filesystem library assciated function.
Parameters
[in] path The path to check.
Returns
An integer value.
Return values
1 if the path is a directory.
0 if the path is not a directory.
-1 if an error occured.
Definition at line 40 of file FMC_dir_wrapper.cpp.
References FMC_isDir_().
FMC_isEmpty()
int FMC_isEmpty (const char * path)
Checks if a directory is empty.
Author
Axel PASCON
Date
2023
This function is a wrapper around the C++ filesystem library assciated function.
Parameters
[in] path The path to check.
Returns
An integer value.
Return values
1 if the directory is empty.
0 if the directory is not empty.
-1 if an error occured.
Definition at line 80 of file FMC_dir_wrapper.cpp.
References FMC_isEmpty_().
FMC_isFIFO()
int FMC_isFIFO (const char * path)
Checks if a path is a FIFO.
Author
Axel PASCON
Date
2023
This function is a wrapper around the C++ filesystem library assciated function.
Parameters
[in] path The path to check.
Returns
An integer value.
Return values
1 if the path is a FIFO.
0 if the path is not a FIFO.
-1 if an error occured.
Definition at line 70 of file FMC_dir_wrapper.cpp.
References FMC_isFIFO_().
FMC_isOther()
int FMC_isOther (const char * path)
Checks if a path is of an unknown type.
Author
Axel PASCON
Date
2023
This function is a wrapper around the C++ filesystem library assciated function.
Parameters
[in] path The path to check.
Returns
An integer value.
Return values
1 if the path is of an unknown type.
0 if the path is not of an unknown type.
-1 if an error occured.
Definition at line 75 of file FMC_dir_wrapper.cpp.
References FMC_isOther_().
FMC_isRegFile()
int FMC_isRegFile (const char * path)
Checks if a path is a regular file.
Author
Axel PASCON
Date
2023
This function is a wrapper around the C++ filesystem library assciated function.
Parameters
[in] path The path to check.
Returns
An integer value.
Return values
1 if the path is a regular file.
0 if the path is not a regular file.
-1 if an error occured.
Definition at line 45 of file FMC_dir_wrapper.cpp.
References FMC_isRegFile_().
FMC_isSocket()
int FMC_isSocket (const char * path)
Checks if a path is a socket.
Author
Axel PASCON
Date
2023
This function is a wrapper around the C++ filesystem library assciated function.
Parameters
[in] path The path to check.
Returns
An integer value.
Return values
1 if the path is a socket.
0 if the path is not a socket.
-1 if an error occured.
Definition at line 65 of file FMC_dir_wrapper.cpp.
References FMC_isSocket_().
FMC_isSymLink()
int FMC_isSymLink (const char * path)
Checks if a path is a symbolic link.
Author
Axel PASCON
Date
2023
This function is a wrapper around the C++ filesystem library assciated function.
Parameters
[in] path The path to check.
Returns
An integer value.
Return values
1 if the path is a symbolic link.
0 if the path is not a symbolic link.
-1 if an error occured.
Definition at line 50 of file FMC_dir_wrapper.cpp.
References FMC_isSymLink_().