FManC: src/analyze.h File Reference
analyze.h File Reference
Data Structures
struct FManC_StrOcc
Macros
#define SHARED
Typedefs
typedef struct FManC_StrOcc stringOccurrences
Functions
int copyFileWithoutStrings (const unsigned int argc, char *filePath,...)
size_t countCharInFile (char *filePath)
void free_stringOccurrences (stringOccurrences *toBeDeleted)
stringOccurrences * init_stringOccurences (size_t sizeOfString)
int replaceStringInFile (char *filePath, char *toReplaceString, char *toAddString)
stringOccurrences * searchStringInFile (char *filePath, char *toSearch)
Data Structure Documentation
FManC_StrOcc
struct FManC_StrOcc
Definition at line 25 of file analyze.h.
Data Fields
size_t charCount
long long int * pos
Macro Definition Documentation
SHARED
#define SHARED
Definition at line 18 of file analyze.h.
Typedef Documentation
stringOccurrences
typedef struct FManC_StrOcc stringOccurrences
Definition at line 31 of file analyze.h.
Function Documentation
copyFileWithoutStrings()
int copyFileWithoutStrings (const unsigned int argc, char * filePath, ...)
countCharInFile()
size_t countCharInFile (char * filePath)
Definition at line 14 of file analyze.c.
Referenced by searchStringInFile().
free_stringOccurrences()
void free_stringOccurrences (stringOccurrences * toBeDeleted)
Definition at line 47 of file analyze.c.
References FManC_StrOcc::pos.
Referenced by replaceStringInFile(), and searchStringInFile().
init_stringOccurences()
stringOccurrences * init_stringOccurences (size_t sizeOfString)
Definition at line 35 of file analyze.c.
References FManC_StrOcc::charCount, and FManC_StrOcc::pos.
Referenced by searchStringInFile().
replaceStringInFile()
int replaceStringInFile (char * filePath, char * toReplaceString, char * toAddString)
Definition at line 155 of file analyze.c.
References FManC_StrOcc::charCount, free_stringOccurrences(), getFileExtension, getFileName, getFilePath, MAX_FEXT_SIZE, MAX_FNAME_SIZE, MAX_FPATH_SIZE, FManC_StrOcc::pos, and searchStringInFile().
searchStringInFile()
stringOccurrences * searchStringInFile (char * filePath, char * toSearch)
Definition at line 54 of file analyze.c.
References countCharInFile(), free_stringOccurrences(), getFileName, init_stringOccurences(), and FManC_StrOcc::pos.
Referenced by replaceStringInFile().