name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linux-static-lib-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with: 
        submodules: 'recursive'
#    - name: Install sudo package
#      run: apt update && apt install sudo
    - name: make static lib for linux
      run: make static CC=gcc CCXX=g++
  
  linux-shared-lib-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
#    - name: Install sudo package
#      run: apt update && apt install sudo
    - name: make shared lib for linux
      run: make shared CC=gcc CCXX=g++
      
#  build-stat-win:
#    runs-on: windows-latest
#    steps:
#    - uses: actions/checkout@v3
#
#    - name: Set up MinGW
#      uses: egor-tensin/setup-mingw@v2
#      with:
#        platform: x64
#        
#        
#    - name: make static lib for windows
#      run: mingw32-make stat_win_only
#      shell: cmd
#      
#  build-dyn-win:
#    runs-on: windows-latest
#    steps:
#    - uses: actions/checkout@v3
#
#    - name: Set up MinGW
#      uses: egor-tensin/setup-mingw@v2
#      with:
#        platform: x64
#
#    - name: make dynamic lib for windows
#      run: mingw32-make dyn_win_only
#      shell: cmd
#