site_name: FManC
repo_url: https://github.com/brvtalcake/FManC
repo_name: FManC
copyright: Copyright &copy; 2022 - 2023 Axel PASCON
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/languages/c.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/highlight.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/es/core.min.js
  - js/syntax.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/styles/base16/eighties.min.css
markdown_extensions:
  - toc:
      permalink: True
      toc_depth: 0
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Getting started: 'index.md'
  - API Reference:
    - Filesystem API: 'api_doc/filesystem_api.md'
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
      lang: 
        - en
extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      github: 
        name: github
        checked: false
    actions:
      - accept
      - manage
      - reject
theme:
  highlightjs: True
  hljs_languages:
    - c
    - c++
  name: material
  locale: en
  logo: ./_images_/FManC.png
  favicon: ./_images_/FManC.ico
  icon:
    repo: fontawesome/brands/github
  font:
    #text: Ubuntu
    text: Open Sans
  features:
    - search.suggest
    - search.share
    - content.code.copy
    - content.code.annotate

  palette:
    scheme: slate
    primary: green
    accent: teal
